[env]
QUIZ_LIGHTWEIGHT_VALIDATE = ""
QUIZ_DEV_MODE = ""

[tasks.watch-book]
script = "mdbook serve --open"

[tasks.watch-js]
script = "cd js-extensions && pnpm watch"

[tasks.watch.run_task]
name = ["watch-book", "watch-js"]
parallel = true