[[questions]]
id = "87c3b09e-84d3-49d7-8680-0b2d068a7fc5"
type = "ShortAnswer"
prompt.prompt = "Every executable Rust program must contain a function with the name:"
answer.answer = "main"
context = """
In your program, you add a main function like this:

```
fn main() {
  // your code here
}
```
"""

[[questions]]
id = "0d78d302-eb3d-4ac7-a1ac-f2d661810744"
type = "MultipleChoice"
prompt.prompt = """
Let's say you have the following program in a file `hello.rs`:

```
fn main() {
  println!("Hello world!");
}
```

Say you then run the command `rustc hello.rs` from the command-line. Which statement best describes what happens next?
"""
answer.answer = "`rustc` generates a binary executable named `hello`"
prompt.distractors = [
  "`rustc` will print an error because this is an invalid program",
  "`rustc` executes the program and prints out `Hello world!`",
  "`rustc` reformats `hello.rs` according to the Rust style guide"
]
context = """
Running `rustc` checks and compiles your program, but does not execute it.
"""