# [[questions]]
# type = "ShortAnswer"
# prompt = "What is the keyword used to declare a variable in Rust?"
# answer = "let"

# [[questions]]
# type = "ShortAnswer"
# prompt = "In one sentence, what is the naming convention for constants in Rust?"
# answer = "Constants are named in ALL_CAPS_WITH_UNDERSCORES."

# [[questions]]
# type = "ShortAnswer"
# prompt = "In one sentence, what does variable shadowing mean?"
# answer = "Variable shadowing is re-defining an existing variable with a let-binding."

[[questions]]
type = "Tracing"
program = """
fn main() {
  let x = 1;
  println!("{x}");
  x += 1;
  println!("{x}");
}
"""