[[questions]]
type = "MultipleChoice"
prompt.prompt = "The largest number representable by the type `i128` is:"
prompt.choices = [
  "2<sup>128</sup>",
  "2<sup>128</sup> - 1",
  "2<sup>127</sup>",
  "2<sup>127</sup> - 1"
]
answer.answer = 3
context = """
In general, a signed number with *n* bits can represent numbers between -(2<sup>n - 1</sup>) and 2<sup>n - 1</sup> - 1.
"""

[[questions]]
type = "MultipleChoice"
prompt.prompt = "If `x : u8 = 0`, what will happen when computing `x - 1`?"
prompt.choices = [
  "It will always panic.",
  "It will always return 255.",
  "It depends on the compiler mode."  
]
answer.answer = 2
context = """
This expression will panic in debug mode and return 255 in release mode.
"""

[[questions]]
type = "Tracing"
prompt.program = """
fn main() {
  let x: fsize = 2.0;
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 2
context = """
The type `fsize` does not exist. Floats must be either `f32` or `f64`.
"""