[[questions]]
id = "2c7132e1-c703-45cb-819f-9f37d3f97c20"
type = "MultipleChoice"
prompt.prompt = """
At the end of this function, Rust will call `drop` on which variables:
```
fn main() {
  let s1 = String::from("a");
  let s2 = String::from("b");
  let s3 = s2;
}
```
"""
answer.answer = "`s1` and `s3`"
prompt.distractors = [ "`s1`, `s2`, and `s3`", "`s2` and `s3`", "`s3`" ]
prompt.answerIndex = 2
context = """
`s2` is not dropped because it is moved into `s3`.
"""

[[questions]]
id = "cff07b34-223f-4c82-a138-f9120b99dcfe"
type = "Tracing"
prompt.program = """
fn main() {
  let x = String::from("hello");
  let mut y = x;
  y.push_str(" world");
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 5
context = """
It is illegal to use `x` after moving it into `y`.
"""

[[questions]]
id = "86d55560-8e6a-4b89-b979-23398c91ed55"
type = "Tracing"
prompt.program = """
fn main() {
  let a = {
    let mut b = String::from("hello");
    b.push_str(" world");
    b
  };
  println!("{a}")
}
"""
answer.doesCompile = true
answer.stdout = "hello world"
context = """
It is legal to move a value from a nested scope to an outer scope.
"""