[[questions]]
id = "31b20096-6c13-4626-b253-4cf93e9f1e4a"
type = "MultipleChoice"
prompt.prompt = "Why does the type `String` not implement the `Copy` trait?"
answer.answer = "Because a `String` owns a pointer to data on the heap"
prompt.distractors = [
  "Because a `String` cannot be shallow-copied",
  "Because the `char` type does not implement `Copy`",
  "Because `Copy` is only implemented for primitive types"
]
context = """
Because a `String` owns a pointer to data on the heap, 
a shallow-copy would cause multiple strings to have ownership over the same heap data.
"""

[[questions]]
id = "2a244dde-f20c-4424-984c-5d2f5c3a7ba9"
type = "Tracing"
prompt.program = """
fn main() {
  let x = String::from("hello");
  let mut y = x.clone();
  y.push_str(" world");
  println!("{x}");
}
"""
answer.doesCompile = true
answer.stdout = "hello"
context = """
Because `y` is a deep copy of `x`, the mutation to `y` does not affect `x`.
"""
