[[questions]]
id = "5080616f-6f4c-43f7-aa3a-8b23f2798937"
type = "Tracing"
prompt.program = """
fn incr(n: &mut i32) {
  *n += 1;
}

fn main() {
  let mut n = 1;
  incr(&n);
  println!("{n}");
}
"""
answer.doesCompile = false
answer.lineNumber = 7
context = """
Although `n` is marked as `mut`, the reference to `n` must also be marked as `mut`. So a valid version of this program would say `incr(&mut n)`.
"""
promptExplanation = true


[[questions]]
id = "e9846c5d-1254-4420-9986-dae4af86b9af"
type = "Tracing"
prompt.program = """
fn main() {
  let mut s = String::from("hello");
  let s2 = &s;
  let s3 = &mut s;
  s3.push_str(" world");
  println!("{s2}");
}
"""
answer.doesCompile = false
answer.lineNumber = 6
context = """
<<<<<<< HEAD
It is illegal to use a mutable reference to a value (`s3`) while an immutable reference 
is live (`s2`). The last line of the error is the `println` on line 6, because if you 
deleted that line, then this program would compile.
=======
It is illegal to use a mutable reference to a value (`s3`) while an immutable reference is live (`s2`). 
Note that the program is ok until `println!("{s2}")`, because that extends the live range of `s2` to overlap with `s3`.
Therefore the last line involved in this error is line 6.
>>>>>>> 86eaa7e6 (Fix some wording in a few questions)
"""