[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which control flow construct would be most idiomatic to use in the following function?

```
enum Location {
  Point(i32),
  Range(i32, i32)
}

fn print_range_max(loc: &Location) {  
  // print the second field of Range, if loc is a Range
}
```
"""
prompt.choices = [
  "`match`",
  "`if let`",
]
answer.answer = 1
context = """
If the function only has an effect in one condition, an `if let` is most idiomatic.
"""

[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which control flow construct would be most idiomatic to use in the following function?

```
enum Location {
  Point(i32),
  Range(i32, i32)
}

fn get_start(loc: &Location) -> i32 { 
  // return the first field of Range or the only field of Point  
}
```
"""
prompt.choices = [
  "`match`",
  "`if let`",
]
answer.answer = 0
context = """ 
If the function needs to return a value for each condition, then a `match` is most appropriate.
"""
