[[questions]]
id = "4e18f340-e336-43c5-9a95-79dec1f49945"
type = "ShortAnswer"
prompt.prompt = "What is the keyword you use at the start of an absolute path to an item in the current crate?"
answer.answer = "crate"
context = """
For example, an absolute path to item `b` in module `a` would be `crate::a::b`.
"""

[[questions]]
id = "256d0ce2-da89-4b44-94da-177634fc633a"
type = "Tracing"
prompt.program = """
pub mod foo {
  fn a() { println!("a"); }
  mod bar {
    pub fn b() { println!("b"); }
  }
}

fn main() {
  foo::bar::b();
}
"""
answer.doesCompile = false
answer.lineNumber = 9
context = """
`b` is not accessible to `main` because the module `bar` is not marked as `pub`.
"""

[[questions]]
id = "5e78e2e4-81dc-42b2-8527-f08b5117982f"
type = "Tracing"
prompt.program = """
pub mod foo {
  pub mod bar {
    pub fn b() { println!("b");  }
  }
  pub fn a() { bar::b(); }
}

fn main() {
  foo::a();
}
"""
answer.doesCompile = true
answer.stdout = "b"
context = """
It is valid within `foo` to use a relative path to refer to items within `bar`.
"""
