[[questions]]
type = "ShortAnswer"
prompt.prompt = "What is the name of the environment variable you should set to `1` to see the backtrace of a panic?"
answer.answer = "RUST_BACKTRACE"
context = """
For example, you can run from the command line: `RUST_BACKTRACE=1 cargo run`
"""

[[questions]]
type = "MultipleChoice"
prompt.prompt = "Which of the following is NOT a good reason to use a panic?"
prompt.choices = [
  "The program is about to perform a dangerous operation",
  "The program should stop executing as soon as possible",
  "The program has reached an error state which should be communicated to a caller function",
  "The program has reached an unrecoverable error state"
]
answer.answer = 2
context = """
A panic should not be used to communicate failure *within* the program. The default assumption is that caller functions
will not try to catch panics.
"""