[[questions]]
type = "MultipleChoice"
prompt.prompt = "Which of these statements best describes why `File::open` returns a `Result` and not an `Option`?"
prompt.choices = [
  "Because `Result` represents the possibility of failure, while `Option` cannot represent failures",
  "Because `Result` uses fewer bytes at runtime than `Option` to represent failures",
  "Because `Result` represents errors the same way as the underlying system calls",
  "Because `Result` can represent why an operation failed, and file opening can fail for many reasons"
]
answer.answer = 3
context = """
`Option` can just represent *that* an operation has failed, but `Result` can explain *why* the operation has failed.
"""