[[questions]]
id = "214d5183-5a88-4f5e-a54b-09909bd50bf7"
type = "Tracing"
prompt.program = """
fn main() {
    let mut v = vec![(1, 2), (3, 4)].into_iter();
    let mut sum = 0;    
    while let Some(t) = v.next() {
        let (_, n) = t;
        sum += n;
    }
    println!("{sum}");
}
"""
answer.doesCompile = true
answer.stdout = "6"
context = """ 
This example provides a valid use of `while let` matching and `let` matching. Note that you
could combine them, e.g.

```
while let Some((_, n)) = v.next() {
    /* ... */
}
```
"""