[[questions]]
id = "d172fc53-0220-4ff4-83c9-9c0a6834dd8e"
type = "MultipleChoice"
prompt.prompt = "What is 1 + 1? (Try clicking a wrong answer.)"
prompt.choices = [
  "0",
  "-999",
  "11",
  "2"
]
answer.answer = 3
context = """
See *Principia Mathematica* for an explanation of this fact.
"""